[package]
name = "vm"
version = "0.1.0"
edition = "2024"

[lib]
name = "vm"
path = "src/vm.rs"


[dependencies]
object = { path = "../object"}
compiler = { path = "../compiler"}
code = { path = "../code"}
