[package]
name = "repl"
version = "0.1.0"
edition = "2021"

[[ bin ]]
name = "repl"
path = "src/main.rs"

[dependencies]
lexer = { path ="../lexer" }
parser = { path = "../parser"}
object = { path = "../object"}
compiler = { path = "../compiler"}
vm = { path = "../vm"}
