[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[lib]
name = "parser"
path = "src/parser.rs"

[dependencies]
lazy_static = "1.5.0"
lexer = { path = "../lexer" }
ast = { path = "../ast" }
