[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[lib]
name = "compiler"
path = "src/compiler.rs"

[dependencies]
ast = { path ="../ast" }
code = { path = "../code"}
object = { path = "../object"}
